<?php

namespace AppBundle\Repository;

/**
 * Art_articleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Art_articleRepository extends \Doctrine\ORM\EntityRepository
{
}
