<?php

namespace AppBundle\Repository;

/**
 * TypeArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeArticleRepository extends \Doctrine\ORM\EntityRepository
{
}
